/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/yNPa3yBaxmq
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Rubik } from 'next/font/google'
import { Libre_Franklin } from 'next/font/google'

rubik({
  subsets: ['latin'],
  display: 'swap',
})

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
'use client';

import styles from './waiting.module.css'
import { useRouter } from 'next/navigation';
import React, { useState, useRef, useEffect } from 'react';

export default function Waiting() {
  const router = useRouter();

  useEffect(() => {
    const timer = setTimeout(() => {
      router.push('/dashboard'); 
    }, 2000);

    // Cleanup the timer on component unmount
    return () => clearTimeout(timer);
  }, [router]);
  
  return (
    <div className={styles.waitContainer}>
    <div className="flex min-h-[100dvh] flex-col items-center justify-center bg-background">
      <div className="space-y-6 text-center">
        <h1 className="text-3xl font-bold tracking-tight text-foreground sm:text-4xl md:text-5xl">
          Building your personalised care plan
        </h1>
        <div className="flex items-center justify-center">
          <div className="h-8 w-8 animate-spin text-primary" />
          <span className="ml-2 text-muted-foreground">Loading...</span>
        </div>
      </div>
    </div>
    </div>
  )
}
