name: Deploy App Engine using gcloud
on:
  push:
    branches:
      - deploy_backend

jobs:
  DeployBackend:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      # actions/checkout MUST come before auth
      - name: 'Checkout'
        uses: 'actions/checkout@v3'

      - name: 'Authenticate to GCP as Infrastructure SA for deployment'
        uses: 'google-github-actions/auth@v1'
        with:
          export_environment_variables: true
          project_id : ${{ vars.PROJECT_ID }}
          workload_identity_provider: ${{ vars.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ vars.INFRA_SA_EMAIL }} # Use your Infrastructure SA to manage resources

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: 'Deploy App Engine'
        id: deploy
        run: |
          set -e
          
          gcloud app deploy backend/app.yaml --service-account="${{ vars.WORKLOAD_SA_EMAIL }}"
          
          url=$(gcloud app describe --format="value(defaultHostname)")
          echo "url=${url}" >> "${GITHUB_OUTPUT}"

      # Example of using the output
      - name: 'Poke App Engine'
        run: 'curl "${{ steps.deploy.outputs.url }}"'